deployment: preprod
version: v1
andamio_protocol_treasury:
andamio_services_treasury:
systems:
  global-state:
    addresses:
      params_ref_validator_address: ""
      global_state_address: addr_test1xrrkcdgg3tyzdj9qu628erlh3kx5f9tcn0rjjsvm8ge5xpvke8x9mpjf7aerjt3n3nfd5tnzkfhlprp09mpf4sdy8dzqs6wq6p
    tokens:
      access_token_policyid: c76c35088ac826c8a0e6947c8ff78d8d4495789bc729419b3a334305

  index-validators:
    addresses:
      index_ref_address: ""
      index_scripts_address: ""
    tokens:
      access_token_policyid: c76c35088ac826c8a0e6947c8ff78d8d4495789bc729419b3a334305
      init_index_policyid: ""
      index_admin_policyid: ""
      index_ref_policyid: ""

  instance:
    addresses:
      instance_governance_scripts_address: ""
      instance_provider_scripts_address: ""
      instance_scripts_address: ""
    tokens:
      instance_provider_policyid: ""
      instance_policyid: ""
      instance_admin_policyid: ""


  