deployment: preprod
version: v1
andamio_protocol_treasury: addr_test1qpuwf43fgc6wx3ed20c6wgm267t84ypxdc02qrdnjqkwgtlxakhvwf2dxzsqncufwrrau2ftmv79kh5dl9djq4jly3xspgyfcz
andamio_services_treasury:
systems:
  global-state:
    addresses:
      params_ref_validator_address: ""
      global_state_address: addr_test1xr7xs02kjwr7v3frqrx4exearkd5nmx5ashhzsj5l3nja7yke8x9mpjf7aerjt3n3nfd5tnzkfhlprp09mpf4sdy8dzq6ptcdp
    tokens:
      access_token_policyid: c76c35088ac826c8a0e6947c8ff78d8d4495789bc729419b3a334305

  index-validators:
    addresses:
      index_ref_address: addr_test1xqzp3cel9p95shlsaertqrt0wcmym5y780ljmca80k4u8ruke8x9mpjf7aerjt3n3nfd5tnzkfhlprp09mpf4sdy8dzqdxy5xn
      index_scripts_address: addr_test1xrrkcdgg3tyzdj9qu628erlh3kx5f9tcn0rjjsvm8ge5xpvke8x9mpjf7aerjt3n3nfd5tnzkfhlprp09mpf4sdy8dzqs6wq6p
    tokens:
      access_token_policyid: c76c35088ac826c8a0e6947c8ff78d8d4495789bc729419b3a334305
      init_index_policyid: ""
      index_admin_policyid: ""
      index_ref_policyid: ""

  instance:
    addresses:
      instance_governance_scripts_address: addr_test1xzx8yjaufqwec9vnze5a4mqpuxuxasks9tvut534cc44ft5ke8x9mpjf7aerjt3n3nfd5tnzkfhlprp09mpf4sdy8dzqs0v3wq
      instance_provider_scripts_address: addr_test1xra9ne75azha7sa3pq5letmml6ugsh4fppwhfhk088jm8tyke8x9mpjf7aerjt3n3nfd5tnzkfhlprp09mpf4sdy8dzq0lvt5x
      instance_scripts_address: addr_test1xpyga27u94rsgnzdgu4df3w8mes538dymt5dhqlszgmfxeyke8x9mpjf7aerjt3n3nfd5tnzkfhlprp09mpf4sdy8dzqcrqkuk
    tokens:
      instance_provider_policyid: fa59e7d4e8afdf43b10829fcaf7bfeb8885ea9085d74decf39e5b3ac
      instance_policyid: 488eabdc2d47044c4d472ad4c5c7de61489da4dae8db83f012369364
      instance_admin_policyid: ""


  