// AUTO-GENERATED by scripts/generate-validators.mjs — DO NOT EDIT BY HAND.
//
// Source of truth:
//   - machine skeleton (name + authorized actions): public/yaml/contracts/plutus.json (pinned blueprint)
//   - curated annotations (layer · purpose · governs): public/yaml/contracts/validators-annotations.json
//
// Regenerate with: npm run docs-validators
// A prebuild drift guard (scripts/check-validators-manifest.ts) fails the build
// if this file diverges from the blueprint, so it cannot silently go stale.

export type ValidatorLayer =
  | "Global registry"
  | "Instances"
  | "Course"
  | "Project";

export interface ValidatorEntry {
  /** Blueprint validator name, e.g. "global/global_state". */
  id: string;
  /** Human-friendly display name. */
  name: string;
  /** One of the four protocol layers. */
  layer: ValidatorLayer;
  /** One-line purpose (curated). */
  purpose: string;
  /** Authorized redeemer actions, sourced mechanically from the blueprint. */
  actions: string[];
  /** What token/state this validator mints/burns/governs (curated, tokens inline). */
  governs: string;
}

/** Canonical layer order, top (global) to bottom (project). */
export const VALIDATOR_LAYERS: ValidatorLayer[] = ["Global registry","Instances","Course","Project"];

export const VALIDATORS: ValidatorEntry[] = [
  {
    "id": "global/global_state",
    "name": "Global State",
    "layer": "Global registry",
    "purpose": "The protocol-wide registry of participant identities and their local-state pointers — the on-chain identity every course and project interaction checks.",
    "actions": [
      "MintLocalState",
      "BurnLocalState",
      "DeleteState",
      "ChangeUserInfo",
      "MoveState"
    ],
    "governs": "Governs the **Access Token** global state. Mints a `g`-prefixed global-state token per registered alias (datum `{alias, local_state_information}`); the user's wallet holds the matching `u`-prefixed **user access token** from the index policy. Records credential-claim attestations back into a user's global state, and moves or retires that state as users enroll, claim, and update."
  },
  {
    "id": "global/global_state_ref",
    "name": "Global State Reference",
    "layer": "Global registry",
    "purpose": "Bootstraps a new entry in the registry's index linked list so the global state stays ordered and append-only.",
    "actions": [
      "NewGlobalRefPair"
    ],
    "governs": "Creates a new global reference pair — the **index linked-list marker** (the `0x20` space-prefixed token in the index policy) carrying `{prev_alias, next_alias}` so each new alias inserts in order. This is the index/reference plumbing behind access-token minting."
  },
  {
    "id": "ls_instances/governance",
    "name": "Governance",
    "layer": "Instances",
    "purpose": "The shared authorization registry for an instance — who may act as a course's teachers or a project's managers.",
    "actions": [
      "Use",
      "AddInstanceCreators",
      "RemoveInstanceCreators",
      "MoveNew"
    ],
    "governs": "Holds the **governance token** (course-governance policy, token name = the courseId) in a UTxO with datum `{participants: [aliases]}`. The same validator backs both course teachers and project managers (the instance-admin role). `AddInstanceCreators`/`RemoveInstanceCreators` edit the participant set; `MoveNew` rolls it forward."
  },
  {
    "id": "ls_instances/instance_provider",
    "name": "Instance Provider",
    "layer": "Instances",
    "purpose": "Authorizes minting and burning on behalf of an instance, letting a course or project's sub-validators issue their own state tokens.",
    "actions": [
      "ProvideMint",
      "ProvideBurn"
    ],
    "governs": "Provides the mint/burn authority (`ProvideMint`/`ProvideBurn`) for instance-scoped tokens — notably the **LocalStateToken**, the UTxO that registers a course/project and embeds that instance's own validator as a script reference."
  },
  {
    "id": "ls_instances/instances",
    "name": "Instances",
    "layer": "Instances",
    "purpose": "Registers a new instance — the on-chain container for a single course or project — and links its local state into the global registry.",
    "actions": [
      "MintInstanceRefScr",
      "RemoveInstanceRefScr",
      "BurnInstance"
    ],
    "governs": "Mints the **LocalStateNFT** (`LocalStateNFT`), whose minting-policy ID **is** the course/project identifier (the courseId/projectId), and the **Local State Registration** token that connects the instance's local state to global V2 state. `MintInstanceRefScr`/`RemoveInstanceRefScr` manage its reference scripts; `BurnInstance` retires it."
  },
  {
    "id": "course/assignment_validator",
    "name": "Assignment Validator",
    "layer": "Course",
    "purpose": "Adjudicates assignment evidence — students submit, teachers accept or refuse.",
    "actions": [
      "Refuse",
      "Accept",
      "StudentAction"
    ],
    "governs": "Drives the assignment lifecycle on the student's Course State UTxO (it mints no token of its own). `StudentAction` submits or updates evidence; `Accept` (a teacher) records the completion that advances the Course State token; `Refuse` rejects the submission."
  },
  {
    "id": "course/course_state",
    "name": "Course State",
    "layer": "Course",
    "purpose": "Tracks each student's enrollment and progress within one specific course.",
    "actions": [
      "MintCourseState",
      "CommitAssignment",
      "BurnCourseState"
    ],
    "governs": "Mints the **Course State token** (course-state policy, parameterized per course; token name = the student's alias, so one enrollment per student per course). The datum holds the student's completed modules and any active assignment commitment. `CommitAssignment` records a commitment; `BurnCourseState` retires the token on credential claim."
  },
  {
    "id": "course/module_scripts",
    "name": "Module Scripts",
    "layer": "Course",
    "purpose": "Manages a course's modules — the published units of learning content and the Student Learning Targets they require.",
    "actions": [
      "MintModule",
      "UpdateModule",
      "BurnModule"
    ],
    "governs": "Mints **module tokens** (module policy; token name = the 32-byte hash of the module's SLT list), held with datum `{courseId, allowed_course_state_ids, prereq_slt_hashes}`. `UpdateModule` revises a module; `BurnModule` removes it."
  },
  {
    "id": "project/contributor_state",
    "name": "Contributor State",
    "layer": "Project",
    "purpose": "Tracks each contributor's enrollment, task commitments, and completed work within one specific project.",
    "actions": [
      "MintContributor",
      "SpendingBurnRewards",
      "BurnContributor",
      "CommitProject",
      "AddCompleted",
      "AdminRemove",
      "AdminAdd"
    ],
    "governs": "Mints the **Contributor State token** (contributor-state policy, parameterized per project; token name = the contributor's alias). The mint redeemer carries prerequisite proof (courseId + completed SLTs). `CommitProject` commits to a task, `AddCompleted` records finished tasks, `SpendingBurnRewards` distributes rewards, `BurnContributor` retires the token on credential claim, and `AdminAdd`/`AdminRemove` are manager overrides."
  },
  {
    "id": "project/escrow1",
    "name": "Task Escrow",
    "layer": "Project",
    "purpose": "Holds task deposits in escrow and settles them when a manager assesses a contributor's work.",
    "actions": [
      "Deny",
      "Refuse",
      "Accept",
      "UserAction"
    ],
    "governs": "Custodies task-escrow UTxOs (datum = the list of task content hashes) plus the treasury deposits backing them. `UserAction` is the contributor's move; `Accept` (a manager) releases the reward and pairs with `contributor_state: AddCompleted`; `Deny`/`Refuse` reject the submission."
  },
  {
    "id": "project/treasury",
    "name": "Treasury",
    "layer": "Project",
    "purpose": "Holds and disburses a project's shared funds and defines its tasks.",
    "actions": [
      "CommitFunds",
      "CommitToken",
      "Manage",
      "BurnTreasuryToken"
    ],
    "governs": "Custodies treasury funds keyed by the **TreasuryScriptV2 token** (treasury-script policy) in a UTxO with datum `{projectId}` and the treasury validator's embedded script reference. `Manage` defines and edits tasks; `CommitFunds`/`CommitToken` add ADA or native tokens; `BurnTreasuryToken` tears the treasury down."
  },
  {
    "id": "project/treasury_token",
    "name": "Treasury Token",
    "layer": "Project",
    "purpose": "Mints the per-task treasury tokens that earmark funds for individual tasks.",
    "actions": [
      "MintTT",
      "BurnTT"
    ],
    "governs": "Mints **treasury tokens** (treasury-token policy; token name = a hash tied to the contributor_state_id) that sit in the treasury/escrow to back each task's reward. `MintTT` issues them; `BurnTT` releases them on payout."
  }
];
